import { mode } from '@chakra-ui/theme-tools'

export const ButtonStyles = {
  baseStyle: {},
  sizes: {},
  variants: {
    origemBlueSolid: (props: any) => ({
      height: "56px",
      width: "208px",
      borderRadius: "8px",
      bg: mode("origem.500", "origem.300")(props),
      boxShadow: "0px 4px 4px rgba(2, 57, 195, 0.30)",
      color: mode("white", "white")(props),
      _hover: {
        boxShadow: "0px 6px 6px rgba(2, 57, 195, 0.30)",
        bg: mode("origem.600", "origem.400")(props),
        transition: "all 0.4s",
      },
    }),
    origemBlueOutline: (props: any) => ({
      height: "56px",
      width: "208px",
      borderRadius: "8px",
      bg: "transparent",
      border: "2px solid",
      borderColor: mode("origem.500", "origem.300")(props),
      boxShadow: "0px 4px 4px rgba(2, 57, 195, 0.30)",
      color: mode("origem.500", "origem.500")(props),
      _hover: {
        boxShadow: "0px 6px 6px rgba(2, 57, 195, 0.30)",
        color: mode("white", "white")(props),
        bg: mode("origem.500", "origem.300")(props),
        transition: "all 0.4s",
      },
    }),
    origemBlueGhost: (props: any) => ({
      height: "56px",
      width: "208px",
      bg: "transparent",
      color: mode("origem.500", "origem.300")(props),
      _hover: {
        boxShadow: "0px 6px 6px rgba(2, 57, 195, 0.30)",
        bg: mode("origem.500", "origem.300")(props),
        color: mode("white", "white")(props),
        transition: "all 0.4s",
      },
    }),
    origemRedSolid: (props: any) => ({
      height: "56px",
      width: "208px",
      borderRadius: "8px",
      bg: mode("red.500", "red.300")(props),
      boxShadow: "0px 4px 4px rgba(217, 42, 42, 0.3)",
      color: mode("white", "white")(props),
      _hover: {
        boxShadow: "0px 6px 6px rgba(217, 42, 42, 0.3)",
        bg: mode("red.600", "red.400")(props),
        transition: "all 0.4s",
      },
    }),
    origemRedOutline: (props: any) => ({
      height: "56px",
      width: "208px",
      borderRadius: "8px",
      bg: "transparent",
      border: "2px solid",
      borderColor: mode("red.500", "red.300")(props),
      boxShadow: "0px 4px 4px rgba(217, 42, 42, 0.3)",
      color: mode("red.500", "red.500")(props),
      _hover: {
        boxShadow: "0px 6px 6px rgba(217, 42, 42, 0.3)",
        color: mode("white", "white")(props),
        bg: mode("red.500", "red.300")(props),
        transition: "all 0.4s",
      },
    }),
    origemRedGhost: (props: any) => ({
      height: "56px",
      width: "208px",
      bg: "transparent",
      color: mode("red.500", "red.300")(props),
      _hover: {
        boxShadow: "0px 6px 6px rgba(217, 42, 42, 0.3)",
        bg: mode("red.500", "red.300")(props),
        color: mode("white", "white")(props),
        transition: "all 0.4s",
      },
    }),
  },
  defaultProps: {},
}
